# Production replica - allow local and Docker network (align with dockerLocalENV)
local   all             all                                     trust
host    all             all             0.0.0.0/0               scram-sha-256
